### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by mmmmmtasty** [albertogeniola/meross-homeassistant#81] opened 2020-05-07 19:46 UTC
Hi

I upgraded my router, then removed and re-added the Meross IoT component and upgraded to the latest version and now I can't control my Meross switches from within home assistant. The HA log just has the following error continually for both devices (mss210 2.0.0 with firmware 2.1.6). On a wifi connection to the same router from the Android app the Meross app works just fine still, it is only HA that has stopped. 

> Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 44, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

I am running hassio 109.3 and component version 20200429.3

If I remove the integration, install 20200423.2, reboot, then reconfigure the integration again it works fine, but only for a few seconds before hitting the same issues. Do you have any advice for troubleshooting steps etc to work out why this is happening?

Thanks

**Comment by clanzett** [comment] 2020-05-08 09:19
Could be related to used meross-iot package. After removing version pinning in manifest it seems to work.

**Comment by albertogeniola** [comment] 2020-05-09 14:15
Duplicate of #77

**Closed by albertogeniola** 2020-05-09 14:15 UTC
