### ISSUE TITLE
No integrations available after installing

### ISSUE THREAD

**Issue by SuperSpe** [albertogeniola/meross-homeassistant#170] opened 2020-11-28 17:27 UTC
Hi, I installed the component via HACS but after reboot I cannot find any "meross" in integrations.
The component is correctly installed, I can see it via HACS, the directory is ok and the log is saying that I am running a custom component that can cause problem, so It's ok.
I'm on rp3 with last versions of hassio hacs and os

**Comment by drasch** [comment] 2020-11-30 00:42
same problem today, no errors in the logs

**Comment by riccardospeggiorin-centropaghe** [comment] 2020-11-30 09:15
I try login from the iOS app and from there I can add Meross from integrations. Still no results on the webui

**Comment by SuperSpe** [comment] 2020-11-30 09:16
I try login from the iOS app and from there I can add Meross from integrations. Still no results on the webui

**Comment by drasch** [comment] 2020-11-30 16:30
after waiting overnight, this seems to have resolved itself for me. Didn't change anything... Thanks!

**Comment by albertogeniola** [comment] 2020-11-30 19:39
Hi @SuperSpe , can you post the error logs?

**Comment by shra1976** [comment] 2020-12-01 13:55
Hi @albertogeniola I have this error:

`Logger: meross_iot.manager
Source: /srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py:632
First occurred: 12:49:00 (108 occurrences)
Last logged: 14:45:31

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-d3ca314784695f4c1f6763c9ce8805cd/subscribe", "messageId": "f6f78c7f631a6a4f25f34ecc9cb2483b", "method": "GET", "namespace": "Appliance.Hub.Mts100.Temperature", "payloadVersion": 1, "sign": "e3c977a228971dfd8d876f658e2ca0cb", "timestamp": 1606829131, "triggerSrc": "Android"}, "payload": {"temperature": [{"id": "010081EA"}]}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-d3ca314784695f4c1f6763c9ce8805cd/subscribe", "messageId": "0f51afa2d0d92d23a1e83316a5f0dd39", "method": "GET", "namespace": "Appliance.Hub.Mts100.Temperature", "payloadVersion": 1, "sign": "c332ecaf65759e83e43a2b794d24a6dd", "timestamp": 1606829136, "triggerSrc": "Android"}, "payload": {"temperature": [{"id": "01008B06"}]}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-d3ca314784695f4c1f6763c9ce8805cd/subscribe", "messageId": "e0d036d432240ffc76a9fc20d371d981", "method": "GET", "namespace": "Appliance.Hub.Mts100.Temperature", "payloadVersion": 1, "sign": "53b7d78140c8c15565d7c3806c85fea7", "timestamp": 1606829141, "triggerSrc": "Android"}, "payload": {"temperature": [{"id": "0100A7FF"}]}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-d3ca314784695f4c1f6763c9ce8805cd/subscribe", "messageId": "288f85a4eceaff34b62a21aca1946b9e", "method": "GET", "namespace": "Appliance.Hub.Mts100.Temperature", "payloadVersion": 1, "sign": "aa0661275af0ea9fdf4086e54bb3947f", "timestamp": 1606829150, "triggerSrc": "Android"}, "payload": {"temperature": [{"id": "0100B3C9"}]}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/838479-d3ca314784695f4c1f6763c9ce8805cd/subscribe", "messageId": "2bd80e93c435533229f094e6026c38e9", "method": "GET", "namespace": "Appliance.Hub.Mts100.Temperature", "payloadVersion": 1, "sign": "2619ae7de3e0f2a14a03c22fb6ac519e", "timestamp": 1606830326, "triggerSrc": "Android"}, "payload": {"temperature": [{"id": "010057D4"}]}}' sent to device uuid 1911087920368626280348e1e911473b. Timeout was: 5 seconds.`

Thanks,
Marco.

**Comment by shra1976** [comment] 2020-12-01 13:57
In the log I have this error too:

> Logger: custom_components.meross_cloud.sensor
> Source: custom_components/meross_cloud/sensor.py:255
> Integration: Meross Cloud IoT (documentation)
> First occurred: 12:49:00 (108 occurrences)
> Last logged: 14:45:31
> 
> Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: CUCINA UUID: 1911087920368626280348e1e911473b Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
> Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: STUDIO UUID: 1911087920368626280348e1e911473b Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
> Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: CAMERA UUID: 1911087920368626280348e1e911473b Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
> Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: CAMERETTA UUID: 1911087920368626280348e1e911473b Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
> Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: SALOTTO UUID: 1911087920368626280348e1e911473b Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
>     return await asyncio.wait_for(future, timeout, loop=self._loop)
>   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
>     raise exceptions.TimeoutError()
> asyncio.exceptions.TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/sensor.py", line 255, in async_update
>     await self._device.async_get_temperature()
>   File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/controller/known/subdevice.py", line 241, in async_get_temperature
>     res = await self._hub._execute_command(method="GET",
>   File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
>     return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
>   File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
>     response = await self._async_send_and_wait_ack(future=fut,
>   File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
>     raise CommandTimeoutError()
> meross_iot.model.exception.CommandTimeoutError

Marco

**Comment by purplepiccolo** [comment] 2020-12-02 06:09
I was able to add it from the android app. Clicked the "+" in the bottom right

**Comment by albertogeniola** [comment] 2020-12-02 19:00
Hi @SuperSpe ,
please do not start new requests on someone's else issue unless the problem is the same. In that case, you should create separated issues.

**Comment by SuperSpe** [comment] 2020-12-03 07:52
@albertogeniola wasn't me 😂
I have no error logs. The problem resolved itself, adding the integration from the iOS App. I rechecked and now I can see and add the integration from web ui too
You can close the issue

**Comment by albertogeniola** [comment] 2020-12-03 08:24
You're right, I am sorry. Closing!

**Closed by albertogeniola** 2020-12-03 08:24 UTC

**Comment by slyoldfox** [comment] 2021-01-15 13:59
I was facing the same issue. I opened a new private window, logged in and then it appeared.
Maybe it's related due to some caching mechanism (in the browser)?
