### ISSUE TITLE
Unit problems with Meross MSS310 plugs

### ISSUE THREAD

**Issue by josntrm** [albertogeniola/meross-homeassistant#365] opened 2022-06-06 13:46 UTC
Hello, 

I am using this integration with four Meross MSS310 plugs and for each plugs i got a lot of warnings in logs regarding units.
For example

-sensor.meross_1_mss310_power_w_main_channel has unit None which is unsupported for device_class power
-The unit of sensor.meross_1_mss310_voltage_v_main_channel (None) does not match the unit of already compiled statistics (V). Generation of long term statistics will be suppressed unless the unit changes back to V. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
-The unit of sensor.meross_1_mss310_current_a_main_channel (None) does not match the unit of already compiled statistics (A). Generation of long term statistics will be suppressed unless the unit changes back to A. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

Is there a way to fix this?

Another issue that may be linked to this one is that after each reboot, the statistics stops working after a while and all i can doo is reload the integration to get it working again.

Thanks

**Comment by chicco83** [comment] 2022-06-06 14:29
I have the same issue from the beginning of use of this integration months ago.
No way to fix it

**Comment by Mangosteen-Yang** [comment] 2022-06-09 01:03
I also have issues with MSS310 

It worked for the first day

<img width="387" alt="image" src="https://user-images.githubusercontent.com/4507754/172742388-42ff1ac1-2d23-4abf-be8a-71cfce6183d2.png">

**Comment by belikh** [comment] 2022-06-10 06:28
Please see pull request #366 which fixes this.

until the pull request is accepted, there's one simple fix in sensor.py of the custom component.

change 
self._attr_unit_of_measure     to       self._attr_**native_**unit_of_measure

**Comment by chicco83** [comment] 2022-06-10 08:50
i confirm that fix works

**Comment by rohrsh** [comment] 2022-06-11 10:57
Not sure if this is the same issue, but I noticed a warning in my Statistics page today: 

**The unit ('') of this entity doesn't match a unit of device class 'power'** 

_"The unit of your entity is not a supported unit for the device class of the entity, power. 
Statistics can not be generated until this entity has a supported unit.
If this unit was provided by an integration, this is a bug. Please report an issue."_

**Comment by belikh** [comment] 2022-06-11 11:10
> **The unit ('') of this entity doesn't match a unit of device class 'power'**
this is the same issue

**Comment by belikh** [comment] 2022-06-11 11:11
Duplicate of #364

**Comment by albertogeniola** [comment] 2022-06-12 13:01
Hi @belikh ,
thanks a lot for the PR, I've merged it and released v1.2.4. Could you please update via HACS and report back if that's working now?

**Comment by belikh** [comment] 2022-06-13 00:46
No problem, glad I could help. 
I've updated via HACS and can confirm issue is resolved with the PR.  Thanks.

**Comment by albertogeniola** [comment] 2022-06-18 10:54
Great, thanks for the good work.

**Closed by albertogeniola** 2022-06-18 10:54 UTC
Labels: bug, waiting validation
