### ISSUE TITLE
mrs100

### ISSUE THREAD

**Issue by thebadboyltz** [albertogeniola/meross-homeassistant#484] opened 2024-01-09 20:35 UTC
**Describe the bug**

**Your environment**
HomeAssistant version: -- 11.4 --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- PLEASE SPECIFY --

I am having a problem with my MRS100 switches, the up or down command works but the status feedback does not work.
If I close a shutter with the MRS100 local remote control, the feedback always indicates open in HA.

Do you have an idea of ​​the problem.
THANKS

**Comment by viktor56240** [comment] 2024-01-10 07:08
+1

**Comment by Ginxo** [comment] 2024-01-18 09:43
+1

**Comment by pyrexfm** [comment] 2024-02-03 12:23
Same. Also it's not possible to set the position

**Comment by pyrexfm** [comment] 2024-02-03 12:27
Same. But found this in the code comments:
`        # So far, the Roller Shutter RST100 supports position, but it looks like it is fake and not reliable.
        # So we don't support that on HA neither.`

Seems like it is going to be complicated

**Comment by thebadboyltz** [comment] 2024-03-14 22:06
hello, is there any hope that the MRS100 will be 100% functional one day, I am willing to pay for it to work.

If my shutters are closed and I restart HA, it tells me that they are all open.

If I were as competent as "albertogeniola or others", I would even make the modifications to benefit the community, unfortunately I am terrible at programming :-(

**Comment by Ginxo** [comment] 2024-03-15 07:06
> hello, is there any hope that the MRS100 will be 100% functional one day, I am willing to pay for it to work.
> 
> If my shutters are closed and I restart HA, it tells me that they are all open.
> 
> If I were as competent as "albertogeniola or others", I would even make the modifications to benefit the community, unfortunately I am terrible at programming :-(

well unless someone correct me, I'm afraid we are stuck by meros service integration here since it is not exposing real position, see [documentation comment](https://albertogeniola.github.io/MerossIot/api-reference/controller/mixins/rollershutter.html#meross_iot.controller.mixins.roller_shutter.RollerShutterTimerMixin.get_position), according to it there's nothing between 0 a 100.
About the problem you mention @thebadboyltz I would recommend you to check whether there is a related open ticket otherwise just open a new one, I'm not facing it on my installation TBH.

**Comment by thebadboyltz** [comment] 2024-03-15 08:50
sorry for asking a stupid question, but in the official MEROSS application there is state feedback so it must be possible (for someone who knows about it).

where should I go to open a ticket?

THANKS

**Comment by Ginxo** [comment] 2024-03-15 09:04
> sorry for asking a stupid question, but in the official MEROSS application there is state feedback so it must be possible (for someone who knows about it).
> 
> where should I go to open a ticket?
> 
> THANKS

not stupid question at all... maybe @albertogeniola can bring some light here. I'm glad to help in case this is possible

**Comment by pyrexfm** [comment] 2024-03-15 09:50
Yes, that tells me this should work. @albertogeniola if you want you could enable this and us that have the MRS100 could help you test this!

If you don't have time and could explain give me some pointers I can try (have some programming experience but never did anything in HA).

**Comment by Ginxo** [comment] 2024-03-15 11:04
@albertogeniola I would say the missing point (at least for me) is about how to access meross API, once I get it I will be able to at least test whether this is feasible

**Comment by thebadboyltz** [comment] 2024-03-15 15:42
I really hope someone can do this, that would be fantastic.

**Comment by albertogeniola** [comment] 2024-03-15 17:54
Hi @thebadboyltz and all,

can you please provide some screenshots of the Meross app where you can find the feedback status? Also, can you please provide the HW version and the firmware version of your device?

I own a MRS100 device HW version 2.0.0 (firmware version 2.1.4) and the app does not even report whether the shutter is opened or not. I am curious to see if newer versions of the shutter has added this feature...

**Comment by pyrexfm** [comment] 2024-03-15 18:49
https://github.com/albertogeniola/meross-homeassistant/assets/73044172/88d666f0-c2ac-4cf4-b8dc-59a7104f451e

Firmware 6.6.6
HW version is 8.0.0

**Comment by albertogeniola** [comment] 2024-03-15 21:13
@Ginxo , @pyrexfm ,

you are running newer HW/FW versions of the MRS100: yours expose that functionality. I'll mark this repository as Enhancement. I'll possibly spend some time on adding this feature in the next release.

**Comment by thebadboyltz** [comment] 2024-03-15 21:28
I'm using version 7.6.14 and 7.0.0 and it's like the higher videos. If you can do this in future versions I will support you financially

**Comment by Ginxo** [comment] 2024-04-12 16:10
I've posted for now a solution, see https://github.com/albertogeniola/meross-homeassistant/pull/495 @albertogeniola please review

this is working for me, at least now the percentage is shown on the shutter component.

I'm now working on providing `SET_POSITION` feature for being able to work with a slider
![image](https://github.com/albertogeniola/meross-homeassistant/assets/25130444/1ff0a363-0264-49e5-8cb1-7cc032b8981c)

set position is not working for now, but I'm still trying it... Cheers

**Comment by Ginxo** [comment] 2024-04-12 16:44
slider feature is now posted as a proposal together with the set position feature. See https://github.com/albertogeniola/meross-homeassistant/pull/496
let's wait for @albertogeniola 's approval
Meanwhile you can replace your `custom_components/meross_cloud/cover.py` file by the one from my repo https://github.com/Ginxo/meross-homeassistant/blob/feature/setposition/custom_components/meross_cloud/cover.py

**Comment by albertogeniola** [comment] 2024-04-12 19:04
Hi @Ginxo ,

thanks a lot for the great work. I've added a couple of comments to your PR and requested some changes. In general https://github.com/albertogeniola/meross-homeassistant/pull/495 seems ok (just confirm it will work also without assuming 50% when no position is available from underlying library). The #496 though requires some more work on the low-level library to determine if the specific roller-shutter supports setting the position. Can you please provide a sniffed payload with a hw 7.0.0+ revision? (please have a look at [here](https://albertogeniola.github.io/MerossIot/advanced-topics.html#sniff-device-data) to know how to do so.

**Comment by thebadboyltz** [comment] 2024-04-13 17:43
hello, I tested your code and the percentage return works. This is a big step forward but as written above when restarting the percentage is set to 50% instead of obtaining the true value.

If only I were as competent as you, I would gladly help you but unfortunately in this area I have two left hands.

**Comment by Ginxo** [comment] 2024-04-14 06:12
> hello, I tested your code and the percentage return works. This is a big step forward but as written above when restarting the percentage is set to 50% instead of obtaining the true value.
> 
> If only I were as competent as you, I would gladly help you but unfortunately in this area I have two left hands.

we are working on improving that 50% thing, for now it is more useful than it was, @albertogeniola already guide me on how to sniff the meross app behaviour, we will have something soon :crossed_fingers:

**Comment by albertogeniola** [comment] 2024-04-16 20:08
Hi!
@Ginxo , as mentioned in #495 I've found the reason why the initial position was not reporting correctly. However, as I don't own the most recent MRS100 with the ability of adjusting the position, I need you to test the code on my behalf.

Please, do as follows.
1. Change the `current_cover_position(self):` so that it does not return 50, but it always returns `self._device.get_position(channel=self._channel_id)`.
2. Change the content of `manifest.json` updating the requirements as follows: `"requirements": ["meross_iot==0.4.7.0b1"],`
3. Restart HA and check if this is now working as intended. 

Once I get this info from you, I can work on a new version release.

**Comment by albertogeniola** [comment] 2024-04-16 22:20
Hi!
@Ginxo , as mentioned in #495 I've found the reason why the initial position was not reporting correctly. However, as I don't own the most recent MRS100 with the ability of adjusting the position, I need you to test the code on my behalf.

Please, do as follows.

- Change the `current_cover_position(self):` so that it does not return 50, but it always returns `self._device.get_position(channel=self._channel_id)`.
- Change the content of `manifest.json` updating the requirements as follows: `"requirements": ["meross_iot==0.4.7.0b1"],`
- Restart HA and check if this is now working as intended.

Once I get this info from you, I can work on a new version release.

**Comment by Ginxo** [comment] 2024-04-17 08:28
> Hi! @Ginxo , as mentioned in #495 I've found the reason why the initial position was not reporting correctly. However, as I don't own the most recent MRS100 with the ability of adjusting the position, I need you to test the code on my behalf.
> 
> Please, do as follows.
> 
>     * Change the `current_cover_position(self):` so that it does not return 50, but it always returns `self._device.get_position(channel=self._channel_id)`.
> 
>     * Change the content of `manifest.json` updating the requirements as follows: `"requirements": ["meross_iot==0.4.7.0b1"],`
> 
>     * Restart HA and check if this is now working as intended.
> 
> 
> Once I get this info from you, I can work on a new version release.

already applied suggestion and working. Please find comments on https://github.com/albertogeniola/meross-homeassistant/pull/495 and https://github.com/albertogeniola/meross-homeassistant/pull/496

**Comment by Ginxo** [comment] 2024-04-17 14:03
> I used your COVER.PY, then I modified it like this and I got this result. [Change the `current_cover_position(self):` so that it does not return 50, but it always returns `self._device.get_position(channel=self._channel_id)`.
> 
>     * Change the content of `manifest.json` updating the requirements as follows: `"requirements": ["meross_iot==0.4.7.0b1"],`
> 
>     * Restart HA and check if this is now working as intended](url)
> 
> 
> ![IMG_9601](https://private-user-images.githubusercontent.com/153684851/323232193-ad329558-d4f2-4c5d-863f-adac2c117471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjI4NDMsIm5iZiI6MTcxMzM2MjU0MywicGF0aCI6Ii8xNTM2ODQ4NTEvMzIzMjMyMTkzLWFkMzI5NTU4LWQ0ZjItNGM1ZC04NjNmLWFkYWMyYzExNzQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNDAyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmQwMjRjYTViMDNmODAxM2JlOWEyMjZlZWFlNzg1MzEwYzc1MjRjNzY2MGQ1NmJiMGViYjFmMzE3N2IxZTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kq--YXFsSY7KkVCU7tqpBChoXQWwLu-SS7bbhmUxbkw) ![IMG_9602](https://private-user-images.githubusercontent.com/153684851/323232203-e12b1d05-df1c-4a6d-ac07-5ec464b7b7e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjI4NDMsIm5iZiI6MTcxMzM2MjU0MywicGF0aCI6Ii8xNTM2ODQ4NTEvMzIzMjMyMjAzLWUxMmIxZDA1LWRmMWMtNGE2ZC1hYzA3LTVlYzQ2NGI3YjdlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNDAyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTEwZDMxZWNmNGQ2NzFhNjUzNTNlNzdiZGVlMmRmYTgxOGNkYWZjOTE1ZGI0YmU5NGRlOThmZTZhMDIwYzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XyDxS5J4v0VLXgugxEgKXVlMUAcMhvYpGYQd3Xk-Nh8) ![IMG_9603](https://private-user-images.githubusercontent.com/153684851/323232206-62c8a2ce-f8d5-4c4d-b88e-62c78249d4a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjI4NDMsIm5iZiI6MTcxMzM2MjU0MywicGF0aCI6Ii8xNTM2ODQ4NTEvMzIzMjMyMjA2LTYyYzhhMmNlLWY4ZDUtNGM0ZC1iODhlLTYyYzc4MjQ5ZDRhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNDAyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDQyYzBhY2FiNjlhMjYwODliNGVmMTRmYTNkMDBlN2QzNmQyYjk4MTc4ZTI4MTE0ZTBjZDFkOGQ0ODFjNTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wB3C8vFFYheChaA82t-DMKP4nC2EKPMxVbXl3tcbUEY)

just to be sure, you can take latest code from https://github.com/albertogeniola/meross-homeassistant/pull/496/files
I don't have that behaviour :thinking:

**Comment by thebadboyltz** [comment] 2024-04-17 15:25
Fantastic, it works wonderfully. You are the best

**Comment by albertogeniola** [comment] 2024-04-17 21:32
Hi all! Just be patient, the feature is almost there. I just need to perform some minor adjustments on the low-level library and then I'll release a newer version of this component with this feature enabled. 

I'll keep you posted!

**Comment by albertogeniola** [comment] 2024-04-25 13:13
Hi all! 
I've just released a new version (v1.3.0) on HACS with some improvements. Improved support for MRS100 has been added. Can you please try it and report back if working as expected?

**Comment by Ginxo** [comment] 2024-04-25 13:20
thanks @albertogeniola 
did you really released `v1.3.0` ? :thinking: 
I just see `v1.2.13` is the release process still ongoing? 
![image](https://github.com/albertogeniola/meross-homeassistant/assets/25130444/7ff6d540-01b4-4e44-84f2-c702114550fe)

**Comment by Ginxo** [comment] 2024-04-25 14:03
> Hi all! I've just released a new version (v1.3.0) on HACS with some improvements. Improved support for MRS100 has been added. Can you please try it and report back if working as expected?

everything working as expected after upgrading to `v1.3.0`

**Comment by albertogeniola** [comment] 2024-04-25 18:07
Great to hear that! Closing as done.

**Closed by albertogeniola** 2024-04-25 18:07 UTC
Labels: Feature request, waiting validation
