### ISSUE TITLE
Not recovering from timeout - meross-homeassistant-20200423.2 

### ISSUE THREAD

**Issue by antivirus68** [albertogeniola/meross-homeassistant#72] opened 2020-04-25 08:01 UTC
I've installed meross-homeassistant-20200423.2, on HA 0.108.8.

It worked fine for some hours then tonight I got this message and all the devices went to unavailable state and they didn't come back anymore.
This is the error message.

```
2020-04-25 01:31:26 ERROR (SyncWorker_1) [custom_components.meross_cloud.common] Component version: 0.3.4.4, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 35, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 296, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-04-25 01:31:27 ERROR (SyncWorker_0) [custom_components.meross_cloud.common] Component version: 0.3.4.4, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/sensor.py", line 30, in update
    self._device.get_status(force_status_refresh=self._device.online)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 296, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```

I've 2 mss310h, 2 msg100, 2 mss310r and 1 mss310.

As soon as I restart HA it works again.

This is the start up log

```
2020-04-25 10:05:06 INFO (MainThread) [custom_components.meross_cloud.version] MerossCloudVersion: 0.3.4.4
2020-04-25 10:05:06 INFO (MainThread) [homeassistant.setup] Setting up meross_cloud
2020-04-25 10:05:06 INFO (MainThread) [homeassistant.setup] Setup of domain meross_cloud took 0.0 seconds.
2020-04-25 10:05:06 INFO (MainThread) [custom_components.meross_cloud] No token was found. Falling back to stored email/password to get a new one.
2020-04-25 10:05:07 INFO (MainThread) [custom_components.meross_cloud] Starting meross manager
2020-04-25 10:05:07 INFO (MainThread) [meross.connection] Initializing the MQTT connection...
2020-04-25 10:05:07 INFO (MainThread) [meross.connection] Client connected to MQTT broker and subscribed to relevant topics.
2020-04-25 10:05:07 INFO (MainThread) [custom_components.meross_cloud] Starting meross cloud connection watchdog
2020-04-25 10:05:07 INFO (MainThread) [homeassistant.components.climate] Setting up climate.meross_cloud
2020-04-25 10:05:08 INFO (MainThread) [homeassistant.components.switch] Setting up switch.meross_cloud
2020-04-25 10:05:08 INFO (MainThread) [homeassistant.components.cover] Setting up cover.meross_cloud
2020-04-25 10:05:08 INFO (MainThread) [homeassistant.components.fan] Setting up fan.meross_cloud
2020-04-25 10:05:08 INFO (MainThread) [homeassistant.components.light] Setting up light.meross_cloud
2020-04-25 10:05:10 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.meross_cloud
```

Please let me know if I can do some other tests.
Marco

**Comment by grea09** [comment] 2020-04-26 14:17
Affected here, restart does not fix the issue. I upgraded daily for the last few weeks with restart to no avail. Often the component will prevent HA to start altogether (connection timeout on HA server) and I need to delete the custom component and restart the entire server.

Here is the error in the log:

```
Logger: custom_components.meross_cloud.common
Source: custom_components/meross_cloud/switch.py:35
First occurred: 24 avril 2020 à 23:41:55 (14558 occurrences)
Last logged: 16:13:03

Component version: 0.3.4.4, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 35, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 296, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```
I'm available for any test.

**Comment by ccorderod** [comment] 2020-04-27 15:56
same behaviour here.

**Comment by grea09** [comment] 2020-04-28 23:19
Updated to the latest release from HACS. Got slightly more detailed logs before HA crashes:

```
2020-04-29 01:16:30 ERROR (SyncWorker_33) [custom_components.meross_cloud.switch] Error occurred.
-------------------------------------
Component version: 0.3.4.4-3
Device info: 
	Name: Bross
	UUID: 1909204351363690802248e1e95255a4
	Type: mss425f
	HW Version: 3.0.0
	FW Version: 3.1.2
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 46, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```

I hope it helps. I really appreciate the work there.

**Comment by silviudc** [comment] 2020-04-29 07:11
I have the same problem, seems to happen if the wifi has a blip (connects/disconnects) and need to restart HA to bring back the devices online

`2020-04-29 08:00:33 ERROR (SyncWorker_5) [custom_components.meross_cloud.common] Component version: 0.3.4.4, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/sensor.py", line 30, in update
    self._device.get_status(force_status_refresh=self._device.online)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 296, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10`

**Comment by maxcanna** [comment] 2020-05-02 08:13
This seems a duplicate of #70

**Comment by albertogeniola** [comment] 2020-05-09 14:13
Duplicate as pointed out by @maxcanna

**Closed by albertogeniola** 2020-05-09 14:13 UTC
