### ISSUE TITLE
New errors with beta 0.116.01b

### ISSUE THREAD

**Issue by chrisbl01** [albertogeniola/meross-homeassistant#145] opened 2020-10-02 14:16 UTC
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:538
First occurred: 10:12:00 AM (4 occurrences)
Last logged: 10:12:00 AM

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/723590-985e8232c7631c23d3a2406e14ca2dcb/subscribe", "messageId": "85e9601e34a3b84ebd4a937bc8cb186a", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "f736e04fdaf158224b3a55c15ec94ed7", "timestamp": 1601647915}, "payload": {}}' sent to device uuid 2005285075590151800848e1e91deb18. Timeout was: 5.0 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/723590-985e8232c7631c23d3a2406e14ca2dcb/subscribe", "messageId": "08f56a67a4f8bda4845019f14b2c8b99", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "9e0365d23e11d590c5f0f09300b95f74", "timestamp": 1601647915}, "payload": {}}' sent to device uuid 2005286553272851800848e1e91e01f2. Timeout was: 5.0 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/723590-985e8232c7631c23d3a2406e14ca2dcb/subscribe", "messageId": "8610ba2a4a4cea5055c219228d1abe03", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "75c0f44abac76195d8d796bc1a200c77", "timestamp": 1601647915}, "payload": {}}' sent to device uuid 2005283323072651800848e1e91de9b8. Timeout was: 5.0 seconds
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/723590-985e8232c7631c23d3a2406e14ca2dcb/subscribe", "messageId": "ea151a45b743ecfaf32c879d4753a9d0", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "ddcdb62f4ac3eb262331e49fd7279de6", "timestamp": 1601647915}, "payload": {}}' sent to device uuid 2005282915218051800848e1e91df644. Timeout was: 5.0 seconds

**Comment by JenniferHatches** [comment] 2020-10-02 20:34
I see the same.

**Comment by arcangelweb** [comment] 2020-10-03 13:40
I can confirm that it doesn't work either

**Comment by coolguymatt** [comment] 2020-10-04 12:05
I get the same error. Also get this:

```Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:285
First occurred: 7:45:23 AM (2 occurrences)
Last logged: 7:48:41 AM

Failed to retrieve abilities for device Garage Door (18120167058930261h0134298f13c495). This device won't be enrolled.

**Comment by arcangelweb** [comment] 2020-10-04 17:35
Everything seems to be working fine with the latest update. (Home Assistant 0.116.0b2)

**Comment by coolguymatt** [comment] 2020-10-05 10:48
I downloaded the integration with commit 4d6fb4f and that seemed to fix it for me.

**Comment by chrisbl01** [comment] 2020-10-05 11:43
All seems to be working with 0.116.0b2 now.  Thanks!

**Comment by coolguymatt** [comment] 2020-10-06 15:18
Whenever my garage door opener loses internet connection, it stays unavailable until I restart Home Assistant. I get the same error messages:

```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:665
First occurred: 11:04:10 AM (1 occurrences)
Last logged: 11:04:10 AM

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/199099-38a2b2408b4ea8ecf06f95ef99270489/subscribe", "messageId": "36126bddac7e19bcb37ee0cc9090bef2", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "bd6b6ad987b1e4a34dba79dd56babadf", "timestamp": 1601996646}, "payload": {}}' sent to device uuid 18120167058930261h0134298f13c495. Timeout was: 5 seconds


```

**Comment by albertogeniola** [comment] 2020-10-10 09:07
Closing in favor of #149

**Closed by albertogeniola** 2020-10-10 09:07 UTC
