### ISSUE TITLE
Warning (Detected I/O inside the event loop)

### ISSUE THREAD

**Issue by daplaji** [albertogeniola/meross-homeassistant#89] opened 2020-05-24 18:16 UTC
There are some messages in registry (below is the first message shown):

Registry detail (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 20:11:52 (1 occurrences)
Last logged: 20:11:52

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()

**Comment by vannetta** [comment] 2020-06-08 08:40
Hi @albertogeniola 
I have the same message than above:

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 10:35:27 AM (1 occurrences)
Last logged: 10:35:27 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()

Could you please do something for it?
Thanks
Vanna

**Comment by daplaji** [comment] 2020-06-08 14:18
Sometimes I have to reboot hassio because the loop cause Meross devices become unavailable

**Comment by vannetta** [comment] 2020-06-08 14:48
Meross devices become unvailables every day at 1:56 AM, 7:56 AM, 1:56 PM. 
I don't need to restart but it needs some minutes to be still ready; but after that every automation concerning them doesn't work anymore.

**Comment by maxcanna** [comment] 2020-06-13 14:34
This is a duplicate of albertogeniola/meross-homeassistant#74

**Closed** 2020-06-13 14:48 UTC
