### ISSUE TITLE
Control Status Led on Socket Plug

### ISSUE THREAD

**Issue by Write** [albertogeniola/meross-homeassistant#468] opened 2023-10-21 22:11 UTC
**Is your feature request related to a problem? Please describe.**
Sockets plugs comes with a LED with Meross Logo that can be disabled in meross_lan integration, it's called "DND"  (Do not disturb) and can be switched off. 

I'm using Local Meross Broker (MQTT). 1.29b1 

**Describe the solution you'd like**
Exposing a switch to turn off the status LED.

**Describe alternatives you've considered**
Black tape, but meross_lan just does it fine, so maybe it can be done ?

**Comment by albertogeniola** [comment] 2024-04-25 13:24
Duplicate of #483 .

**Closed by albertogeniola** 2024-04-25 13:24 UTC
