### ISSUE TITLE
Does't show any Meross products?

### ISSUE THREAD

**Issue by petcol** [albertogeniola/meross-homeassistant#185] opened 2020-12-20 02:47 UTC
**Describe the bug**
Not sure if it's a bug or just me, but, I' fairly sure I've done everything correctly.
I installed using HACS and I can see the folders have been created with the files mentioned using the Terminal I've installed on Home Assistant.  But when I got to >> Configuration > Integrations > Add Integration > "Meross"  doesn't come back with any resutls?

If I cd config/custom_components/meross_cloud  
the files are there like in the tutorial, but when I go to 
Component setup
nothing Merross  comes back blank

any suggestions please.

**Your environment**
HomeAssistant version: -- PLEASE SPECIFY --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- PLEASE SPECIFY --

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by albertogeniola** [comment] 2020-12-30 14:59
Hi @petcol ,
can you reboot your Homeassistant installation and have a look at the logs to see if there is any loading error ?

**Comment by albertogeniola** [comment] 2020-12-30 15:09
Possible duplicate of https://github.com/albertogeniola/meross-homeassistant/issues/181 . 
@petcol : please clear your browser cache and try it again.

**Comment by petcol** [comment] 2020-12-31 00:53
Thanks for getting back to me, it has come good. not sure how or if i did something without realizing but it is now showing them all.

**Comment by albertogeniola** [comment] 2020-12-31 10:35
Glad it worked!

**Closed by albertogeniola** 2020-12-31 10:35 UTC
Labels: waiting validation
