### ISSUE TITLE
mss310 not working

### ISSUE THREAD

**Issue by alex-pardo** [albertogeniola/meross-homeassistant#65] opened 2020-04-15 14:10 UTC
I have the last version of meross-homeassistant and a mss310 with the lastest update. However, I'm not able to control the plug neither to measure the power consumption. I have used the meross_sniffer utility to check if there is any problem with the connection. The result is the following:

`2020-04-15 16:01:40,769 - Sniffer - INFO - DEVICE LISTING VIA HTTP: [{'uuid': '1909120221014125186448e1e9038c19', 'onlineStatus': 1, 'devName': 'TV plug', 'devIconId': 'device012', 'bindTime': 1586696687, 'deviceType': 'mss310', 'subType': 'eu', 'channels': [{}], 'region': 'us', 'fmwareVersion': '2.1.14', 'hdwareVersion': '2.0.0', 'userDevIcon': '', 'iconType': 1, 'skillNumber': '', 'domain': 'mqtt-us.meross.com', 'reservedDomain': 'mqtt-us-alter.meross.com'}]
2020-04-15 16:01:45,261 - Sniffer - DEBUG - Initializing the MQTT connection...
2020-04-15 16:01:45,653 - Sniffer - DEBUG - (Re)Starting the MQTT loop.
2020-04-15 16:01:45,859 - Sniffer - DEBUG - Connected to MQTT Broker
2020-04-15 16:01:45,973 - Sniffer - DEBUG - Subscribed correctly
2020-04-15 16:01:52,377 - Sniffer - INFO - {'payload': {}, 'header': {'messageId': '3f74c9657b2fd21bd3b5918b36da7696', 'method': 'GET', 'from': '/app/410433-0658DA0C38870102BF1C8AA234477C4C/subscribe', 'sign': 'efac24ad1bb10c564d8b672924dfed31', 'namespace': 'Appliance.System.All', 'triggerSrc': 'iOS', 'timestamp': 1586959312, 'payloadVersion': 1}}
2020-04-15 16:02:13,814 - Sniffer - DEBUG - Disconnected from MQTT brocker
2020-04-15 16:02:23,823 - Sniffer - ERROR - Could not collect sysdata/abilities for 1909120221014125186448e1e9038c19
Traceback (most recent call last):
  File "/Users/alexpardo/Envs/phd3/lib/python3.7/site-packages/utilities/meross_sniffer.py", line 192, in main
    sysdata = d.get_sys_data()
  File "/Users/alexpardo/Envs/phd3/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 146, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/Users/alexpardo/Envs/phd3/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/Users/alexpardo/Envs/phd3/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 321, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
`

**Comment by albertogeniola** [comment] 2020-05-09 14:16
Duplicate of #77

**Closed by albertogeniola** 2020-05-09 14:16 UTC
