### ISSUE TITLE
help

### ISSUE THREAD

**Issue by snowmassi** [albertogeniola/meross-homeassistant#87] opened 2020-05-22 10:25 UTC
qualcuno puo aiutarmi 
Dettagli registro (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 10:56:04 (2 occurrences)
Last logged: 10:56:04

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 55: http_client = MerossHttpClient.from_user_password(email=email, password=password)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()

**Comment by maxcanna** [comment] 2020-05-24 16:51
Please avoid opening issues duplicated and with confusing titles. This is a duplicate of #74 😉

**Closed** 2020-06-22 20:20 UTC
