### ISSUE TITLE
Home Assistant UI does not load with the latest update to 20200413.1

### ISSUE THREAD

**Issue by Luke95vl** [albertogeniola/meross-homeassistant#64] opened 2020-04-14 13:08 UTC
After making the last update to 20200413.1 and restarting HA, HA no longer lets me enter the graphical interface with an ERR_CONNECTION_REFUSED message, other components such as SMB work and in the logs I see this cyclic error

```txt
020-04-14 14:47:30 ERROR (SyncWorker_2) [custom_components.meross_cloud.common] Component version: unknown, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 79, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 35, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 139, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 93, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 146, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 321, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-04-14 14:47:40 ERROR (SyncWorker_1) [custom_components.meross_cloud.common] Component version: unknown, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 79, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 35, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 139, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 93, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 146, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 321, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-04-14 14:47:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.stampanti_ender_3 is taking over 10 seconds
2020-04-14 14:47:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.stampanti_usb is taking over 10 seconds
2020-04-14 14:47:50 ERROR (SyncWorker_3) [custom_components.meross_cloud.common] Component version: unknown, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 79, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 35, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 139, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 93, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 146, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 321, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```

**Comment by aferraz** [comment] 2020-04-14 14:57
same for me

**Comment by ollo69** [comment] 2020-04-14 19:12
Confirm, same problem I have to revert to previous version.

**Comment by mirkochip88** [comment] 2020-04-14 19:58
Same

**Comment by stepic** [comment] 2020-04-14 20:51
How to uninstall the addon from command line (hassio)?

**Comment by Luke95vl** [comment] 2020-04-14 21:14
> How to uninstall the addon from command line (hassio)?

via command line I don't know, but if you have SMB sharing you can go into config, custom component and remove the meross folder

**Comment by albertogeniola** [comment] 2020-04-14 21:44
Hi Guys, this seems to be a problem with some sort of conflict. 
@stepic: To remove the plugin from hassio, simply remove the /config/custom_components/meross_cloud folder and you should be good to go.

@Luke95vl : can you print the contents of manifest.json that is contained within the /custom_components/meross_cloud folder? I'm under the impressio that the plugin did not update as expected.

**Comment by Luke95vl** [comment] 2020-04-14 22:12
> Hi Guys, this seems to be a problem with some sort of conflict.
> @stepic: To remove the plugin from hassio, simply remove the /config/custom_components/meross_cloud folder and you should be good to go.
> 
> @Luke95vl : can you print the contents of manifest.json that is contained within the /custom_components/meross_cloud folder? I'm under the impressio that the plugin did not update as expected.
```txt
  "domain": "meross_cloud",
  "name": "Meross Cloud IoT",
  "documentation": "https://www.home-assistant.io/components/meross_cloud",
  "dependencies": ["persistent_notification"],
  "codeowners": ["@albertogeniola"],
  "requirements": ["meross_iot==0.3.3.0", "requests==2.22.0"],
  "config_flow": true,
  "meross_cloud_version": "unknown"
```

**Comment by albertogeniola** [comment] 2020-04-14 22:19
Thanks. Still, I'm unable to find where the problem is: I am unable to reproduce the issue on my test devices. What version of HA are you running?

**Comment by Luke95vl** [comment] 2020-04-14 22:21
@albertogeniola 108.4 but same issue with 108.3

**Comment by albertogeniola** [comment] 2020-04-14 22:32
Are you running HASSIO or homeassistant on a custom linux distribution?

**Comment by Luke95vl** [comment] 2020-04-14 22:33
Hassio with a virtual machine downloaded from the official HA website

**Comment by mirkochip88** [comment] 2020-04-14 22:41
> Are you running HASSIO or homeassistant on a custom linux distribution?

Yes for me.

**Comment by ollo69** [comment] 2020-04-15 00:19
Hi Alberto,

don't know if this can help you, but this is what I have in my logs:

```
2020-04-15 01:51:54 INFO (MainThread) [homeassistant.components.cover] Setting up cover.meross_cloud
2020-04-15 01:51:55 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for climate.termosifone_cucina (<class 'custom_components.meross_cloud.climate.ValveEntityWrapper'>) took 1.067 seconds. Please report it to the custom component author.
2020-04-15 01:51:56 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for climate.termosifone_studio (<class 'custom_components.meross_cloud.climate.ValveEntityWrapper'>) took 1.053 seconds. Please report it to the custom component author.
2020-04-15 01:51:57 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for climate.termosifone_camera_da_letto (<class 'custom_components.meross_cloud.climate.ValveEntityWrapper'>) took 1.061 seconds. Please report it to the custom component author.
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setting up ipp
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setup of domain ipp took 0.0 seconds.
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setting up ifttt
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setup of domain ifttt took 0.0 seconds.
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setting up hue
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setup of domain hue took 0.0 seconds.
2020-04-15 01:51:57 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.setup] Setting up lifx
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.setup] Setup of domain lifx took 0.0 seconds.
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.components.notify] Setting up notify.alexa_media
2020-04-15 01:51:58 INFO (SyncWorker_9) [homeassistant.loader] Loaded alarm_control_panel from homeassistant.components.alarm_control_panel
2020-04-15 01:51:58 INFO (SyncWorker_12) [homeassistant.loader] Loaded systemmonitor from homeassistant.components.systemmonitor
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.setup] Setting up alarm_control_panel
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.setup] Setup of domain alarm_control_panel took 0.0 seconds.
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.alexa_media
2020-04-15 01:51:58 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.legacy
2020-04-15 01:52:14 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of alarm_control_panel platform alexa_media is taking over 10 seconds.
2020-04-15 01:55:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.termosifone_studio is taking over 10 seconds
2020-04-15 01:55:46 ERROR (MainThread) [aioasuswrt.connection] Host timeout.
2020-04-15 01:59:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.termosifone_camera_da_letto is taking over 10 seconds
2020-04-15 01:59:22 INFO (MainThread) [homeassistant.setup] Setting up media_player
2020-04-15 01:59:22 INFO (MainThread) [homeassistant.setup] Setting up mqtt
.......
```

I'm running HA in a Raspberry PI using Raspbian as OS. I'm using v.0.108.3 of HA

I have 4 Meross Valves. The first 3 are started at 1.51.56 with a warning, the last compare after 4 minutes. Then everythings hangs for other 4 minutes, until 1.59.08, then startup go ahead and complete succesfully.
Total time for startup is about 8 minutes vs 30 - 40 sec normal time

After this time long startup everything seems work normally.

Rolling back to previous version everything is ok

**Comment by scott-crs** [comment] 2020-04-15 04:37
Same breaking change issue with upgrade to v.0.108.4. Resolved by commenting out the integration from config.yaml and power cycling. 

# Enable Meross custom component integration
#meross_cloud:
#  username: !secret meross_username
#  password: !secret meross_password

~ $ ha info
arch: armv7
channel: stable
hassos: "3.12"
homeassistant: 0.108.4
hostname: hassio
logging: info
machine: raspberrypi2
supervisor: "217"
supported_arch:
- armv7
- armhf
timezone: America/Vancouver

**Comment by albertogeniola** [comment] 2020-04-15 10:49
Hi guys, sorry to hear that. It seems the last releases are breaking things. I need to remove them from HACS. Could you confirm which is the latest version working for you?

**Comment by ollo69** [comment] 2020-04-15 11:32
For me `20200412.3` is working, though during startup I have this error:

```
....
2020-04-15 02:23:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxx@xxxx.xx for cover
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/cover/__init__.py", line 148, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 244, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/cover.py", line 18, in <module>
    class OpenGarageCover(CoverDevice):
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/cover.py", line 41, in OpenGarageCover
    @cloud_io()
NameError: name 'cloud_io' is not defined
2020-04-15 02:23:48 INFO (MainThread) [homeassistant.components.climate] Setting up climate.meross_cloud
....
```

**Comment by Luke95vl** [comment] 2020-04-15 11:55
I can install 20200412.3, it starts but I can't control the switch, nothing happens

**Comment by scott-crs** [comment] 2020-04-15 14:04
> I can install 20200412.3, it starts but I can't control the switch, nothing happens

v=0.108.0 worked for me.

**Comment by aferraz** [comment] 2020-04-15 14:19
@albertogeniola I don't know if this can help you but with the last version my HA starts after several minutes with errors reported by others and a very hight CPU/RAM consuption.
I also notice errors on chromecast component:
2020-04-15 03:40:37 WARNING (Thread-6) [pychromecast.socket_client] [Googlen Hub Salotto:8009] Heartbeat timeout, resetting connection

After a rollback to 20200412.3 HA works fine

**Comment by httpedo13** [comment] 2020-04-15 16:46
<img width="1106" alt="Schermata 2020-04-15 alle 18 07 20" src="https://user-images.githubusercontent.com/40502451/79364168-3e225900-7f49-11ea-8cb0-d2b837682010.png">

when I turn on the raspberry with hassio I get these errors and the frontend does not start, I am forced to remove the plug and hang up, then it starts. All this with the latest version, now I'm trying to update at 108.4

**Comment by httpedo13** [comment] 2020-04-15 16:51
<img width="1106" alt="Schermata 2020-04-15 alle 18 07 20" src="https://user-images.githubusercontent.com/40502451/79364813-24cddc80-7f4a-11ea-88a7-c7bda7919914.png">

**Comment by albertogeniola** [comment] 2020-04-15 20:43
Hi guys. Can you please report which is the latest version working for you?

**Comment by httpedo13** [comment] 2020-04-15 20:58
Ciao @albertogeniola with 0412.3 version and Hassio 108.5 I get these errors but but hassio restarts correctly.

`2020-04-15 22:53:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry edoardo554@gmail.com for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 148, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 244, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/cover.py", line 18, in <module>
    class OpenGarageCover(CoverDevice):
  File "/config/custom_components/meross_cloud/cover.py", line 41, in OpenGarageCover
    @cloud_io()
NameError: name 'cloud_io' is not defined
2020-04-15 22:53:32 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-04-15 22:53:32 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2020-04-15 22:53:33 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2020-04-15 22:53:35 WARNING (MainThread) [homeassistant.setup] Setup of browser_mod is taking over 10 seconds.
2020-04-15 22:53:41 WARNING (SyncWorker_14) [custom_components.meross_cloud.common] 
2020-04-15 22:53:43 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform meross_cloud is taking over 10 seconds.
2020-04-15 22:53:46 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform meross_cloud is taking over 10 seconds.
2020-04-15 22:53:46 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up meross_cloud platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/meross_cloud/sensor.py", line 172, in async_setup_entry
    sensor_entities = await hass.async_add_executor_job(sync_logic)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/sensor.py", line 160, in sync_logic
    elif plug.type.startswith("mss310") or plug.supports_consumption_reading():
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 179, in supports_consumption_reading
    return CONSUMPTIONX in self.get_abilities()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 151, in get_abilities
    self._abilities = self.execute_command("GET", ABILITY, {})['ability']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 321, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-04-15 22:53:52 WARNING (SyncWorker_14) [custom_components.meross_cloud.common] `

with the latest release and Hassio 108.5 when I go to restart it does not load the frontend, I get the errors and I am forced to unplug and reattach the plug.

**Comment by albertogeniola** [comment] 2020-04-17 08:20
Hi guys,

I've been working on a test release. Who is able to performa a manual installation of a custom component mightbe interested in testing [this one](https://github.com/albertogeniola/meross-homeassistant/issues/67) and report back if that's working as expected. Your help might help me solving the problems with the current version.

**Comment by httpedo13** [comment] 2020-04-17 09:59
I installed it, but when I go to configure the integration it doesn't come out

**Comment by Lorenzo20101999** [comment] 2020-04-17 10:04
It's still not loading homeassistant interface
`2020-04-17 11:55:09 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-17 11:55:09 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-17 11:55:11 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=191 from 2020-04-16 22:37:50.407180)
2020-04-17 11:56:18 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.luce_specchio is taking over 10 seconds
2020-04-17 11:56:18 ERROR (SyncWorker_19) [custom_components.meross_cloud.common] Component version: DEV-0.3.4.1-1, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 35, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 139, in get_status
    self._state = self._get_status_impl()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 93, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 121, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 118, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 294, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-04-17 11:56:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.luce_specchio is taking over 10 seconds
2020-04-17 11:56:28 ERROR (SyncWorker_15) [custom_components.meross_cloud.common] Component version: DEV-0.3.4.1-1, Message: "A command timeout occurred while handling cloud_io function."`

**Comment by lrnzgti** [comment] 2020-04-17 10:51
> It's still not loading homeassistant interface
> 
> ```
> 2020-04-17 12:48:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.luce_specchio is taking over 10 seconds
> 2020-04-17 12:48:47 ERROR (SyncWorker_15) [custom_components.meross_cloud.common] Component version: DEV-0.3.4.1-1, Message: "A command timeout occurred while handling cloud_io function."
> Traceback (most recent call last):
>   File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
>     return func(*args, **kwargs)
>   File "/config/custom_components/meross_cloud/switch.py", line 35, in update
>     self._device.get_status(force_status_refresh=True)
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 139, in get_status
>     self._state = self._get_status_impl()
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 93, in _get_status_impl
>     data = self.get_sys_data()['all']
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 121, in get_sys_data
>     return self.execute_command("GET", ALL, {}, online_check=False)
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 118, in execute_command
>     return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
>   File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 294, in execute_cmd
>     raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
> meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
> ```

I tried removing the config and Home Assistant starts, as soon as I configure meross and reboot it won't start

**Comment by logicup-dev** [comment] 2020-04-17 20:35
I'm running the latest version 20200413.1 with 0.108.5 HassOS 3.13 **without** any issue on my Rpi4

`2020-04-17 10:58:35 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`

**Comment by ollo69** [comment] 2020-04-20 11:02
Still same problem reported [here](https://github.com/albertogeniola/meross-homeassistant/issues/64#issuecomment-613745362) with last version released yesterday.
Rolled-back to version `20200412.3`.

**Comment by httpedo13** [comment] 2020-04-29 18:27
same for me nothing has changed with the new version

> Still same problem reported [here](https://github.com/albertogeniola/meross-homeassistant/issues/64#issuecomment-613745362) with last version released yesterday.
> Rolled-back to version `20200412.3`.

**Comment by albertogeniola** [comment] 2020-04-29 19:12
Hi @httpedo13 , have you tried with 20200429.3?

**Comment by httpedo13** [comment] 2020-04-29 19:59
> Hi @httpedo13 , have you tried with 20200429.3?

yes

**Comment by uvjim** [comment] 2020-06-04 19:19
Also seeing this now.  Everything has been working well for the last couple of weeks and after a reboot I couldn't get back to the UI.

Version details are below...

`Integration version: 20200429.3`

![image](https://user-images.githubusercontent.com/8431065/83801125-81bf5680-a6a0-11ea-86f0-132041f38342.png)

**Comment by albertogeniola** [comment] 2020-07-10 21:40
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).

**Closed by albertogeniola** 2020-07-10 21:40 UTC
Labels: bug
