### ISSUE TITLE
HACS integration not working properly

### ISSUE THREAD

**Issue by bjptwist** [albertogeniola/meross-homeassistant#350] opened 2022-05-09 11:41 UTC
From HACS [page](https://hacs.xyz/docs/publish/start#versions), this repo should be using GitHub releases. However, new versions are shared only as tags which is not enough. New versions of this integration should be shared as Github releases.

Latest release of this repor reports to 2020 and does not even launch in most recent versions of Homeassistant.
As.a workaround solution, one can select **master** from HACS dropdown as the selected version to download this repo. 

<img width="1004" alt="Screenshot 2022-05-09 at 12 46 07" src="https://user-images.githubusercontent.com/956797/167403605-2b714b15-f891-485a-b4ad-8d5a7c9b2e53.png">

**Comment by albertogeniola** [comment] 2022-05-10 18:22
Duplicate of #353.

**Closed by albertogeniola** 2022-05-10 18:22 UTC
