### ISSUE TITLE
HA Energy Dashboard

### ISSUE THREAD

**Issue by eximo84** [albertogeniola/meross-homeassistant#256] opened 2021-08-23 11:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently the power monitor doesnt appear in the Energy Dashboard - https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Describe the solution you'd like**
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by albertogeniola** [comment] 2021-08-25 07:00
Duplicate of #254

**Closed by albertogeniola** 2021-08-25 07:00 UTC
