### ISSUE TITLE
Found 0 devices that require polling. Setting polling interval to 0:00:30

### ISSUE THREAD

**Issue by dustardly** [albertogeniola/meross-homeassistant#121] opened 2020-07-30 10:09 UTC
Hub version 1.0
2 valve working on iPhone app and no one found by plugin , tested on 3 different hassio .

Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:387 
Integration: Meross Cloud IoT (documentation) 
First occurred: 8:06:29 (1 occurrences) 
Last logged: 8:06:29

Found 0 devices that require polling. Setting polling interval to 0:00:30

**Comment by DarwinData** [comment] 2020-08-08 12:22
Still happening with HA 113.3
thanks

**Comment by albertogeniola** [comment] 2020-08-09 19:32
Hi guys, 

can you please report the Hardware and Firmware version of the Valves that show on the Meross App ?

**Comment by DarwinData** [comment] 2020-08-09 23:08
Hi,
Model: mss620
Firmware: 1.1.11
Hardware: 1.0.0
This is an external 2 outlet switch.
thanks

**Comment by albertogeniola** [comment] 2020-08-10 21:02
Hi @dustardly ,

about valves, only ThermostatV3 are currently supported by the library. #110 has been filled for adding support for V2/V1 valves.

@DarwinData : are those switch connecting with an hub or do they connect directly to the wifi? In any case, I have no mss620 to test. Would you mind using the low-level python utility for collecting Meross Data for that device? [Have a look at here](https://albertogeniola.github.io/MerossIot/advanced-topics.html#sniff-device-data).

**Comment by DarwinData** [comment] 2020-08-10 21:14
The mss620 connects directly to my wifi ap. I am running HASS so I am not sure how to run the python utility.  Is it possible? 
thanks

**Comment by albertogeniola** [comment] 2020-08-12 18:08
If the device connects directly to your Wireless AP that is ok. Just do the following:
1. Install the Meross low-level library
    ```bash
    pip install meross_iot --upgrade
    ```
1. Run the Meross Sniffer
    ```bash
    meross_sniffer
    ```
1. Select the device corresponding to the one you want to "sniff" (also, make sure its status is reported as ONLINE)
1. Play with the Meross App and issue some commands to that device
1. Once done, press ENTER, so that the sniffer produces a data.zip file
1. Send that file to me

**Comment by DarwinData** [comment] 2020-08-12 19:24
I went into the 'Terminal' addon and tried pip install meross_iot --upgrade but get a 'command not found: pip' error.
fyi, I am running HA Supervised in Ubuntu on an Intel NUC.
thanks

**Comment by albertogeniola** [comment] 2020-08-13 16:04
Hi @DarwinData ,

you should not run that command from HomeAssistant, I should have told you a bit more. 
You need to use classic Windows/Linux computer, [install Python 3.8](https://www.python.org/downloads/release/python-380/) and then issue the commands I've written in the previous post. Let me know,

Alberto

**Comment by golden-braid** [comment] 2020-08-14 18:26
I have a similar issue with Meross MSS310 Plugs

'Found 18 devices that require polling. Setting polling interval to 0:04:30
18:41:27 – Meross Cloud IoT (WARNING)'

mss310 2.0.0
by Meross
Firmware: 2.1.14

**Comment by dustardly** [comment] 2020-09-02 23:50
Any news on fix it ?

**Comment by albertogeniola** [comment] 2020-09-09 20:59
> I have a similar issue with Meross MSS310 Plugs
> 
> 'Found 18 devices that require polling. Setting polling interval to 0:04:30
> 18:41:27 – Meross Cloud IoT (WARNING)'
> 
> mss310 2.0.0
> by Meross
> Firmware: 2.1.14

What is the problem with this? It's a normal WARNING log, not an error.

@dustardly : I cannot help you without having more details about your devices. 
Would you please run the commands I've [linked here](https://github.com/albertogeniola/meross-homeassistant/issues/121#issuecomment-673028946) from a computer running python 3.7 or 3.8?

**Comment by golden-braid** [comment] 2020-09-09 22:32
> > I have a similar issue with Meross MSS310 Plugs
> > 'Found 18 devices that require polling. Setting polling interval to 0:04:30
> > 18:41:27 – Meross Cloud IoT (WARNING)'
> > mss310 2.0.0
> > by Meross
> > Firmware: 2.1.14
> 
> What is the problem with this? It's a normal WARNING log, not an error.
> 
The Meross MSS310 Plugs i'm using in home assistant are only polling every 4minutes30seconds.  This makes them unusable/unreliable for automations. I am using the power sensors of the plugs to determine the on/off state of items plugged in.
Is there any way to reduce the amount of time it takes to get the state of the plugs?

**Comment by albertogeniola** [comment] 2020-09-10 20:19
Close as it's a duplicate of #109

**Closed by albertogeniola** 2020-09-10 20:19 UTC
