### ISSUE TITLE
Generating No module error

### ISSUE THREAD

**Issue by troykelly** [albertogeniola/meross-homeassistant#1] opened 2019-06-14 00:48 UTC
When added to custom_components - the error below is generated in the log:

```text
2019-06-14 10:46:10 ERROR (MainThread) [homeassistant.config] Unable to import meross_cloud: No module named 'common'
2019-06-14 10:46:10 ERROR (MainThread) [homeassistant.setup] Setup failed for meross_cloud: Invalid config.
```

Home Assistant `0.94.3`
Using component commit [537f78d](https://github.com/albertogeniola/meross-homeassistant/commit/537f78df01bfd9eb703790879d2b9db90f71fd02)

`configuration.yaml`
```yaml
meross_cloud: !include meross_cloud.yaml
```

`secrets.yaml`
```yaml
meross_username: email@example.com
meross_password: "p455w0rD!!"
```

`meross_cloud.yaml`
```yaml
username: !secret meross_username
password: !secret meross_password
```

**Comment by albertogeniola** [comment] 2019-06-14 05:49
Hi @troykelly,

Could you tell me what's inside the custom_components/meross_cloud folder? It seems that common.py file is missing

**Comment by troykelly** [comment] 2019-06-14 05:54
It looks like it's there.
<img width="139" alt="Screen Shot 2019-06-14 at 3 52 01 pm" src="https://user-images.githubusercontent.com/4564803/59486378-7639b500-8ebc-11e9-9ebe-d040ed3903b4.png">

`common.py` (snippet)
```python
# Constants
DOMAIN = 'meross_cloud'
MANAGER = 'manager'
ENROLLED_DEVICES = 'enrolled_devices'
MEROSS_MANAGER = "%s.%s" % (DOMAIN, MANAGER)
.
.
.
def notify_error(hass, notification_id, title, message):
    hass.async_create_task(
        hass.services.async_call(domain='persistent_notification', service='create', service_data={
                                           'title': title,
                                           'message': message,
                                           'notification_id': "%s.%s" % (DOMAIN, notification_id)})
    )
```

**Comment by albertogeniola** [comment] 2019-06-14 06:32
Ok. I did not have enough time to prepare a release on GitHub and by cloning the repository you pulled down more stuff than you need. This might be interfering with homeassistant. 
Could you please remove the following files:
.git from the meross_cloud folder and reboot hassio?

__pycache__
extra
.gitignore
README.md

**Comment by troykelly** [comment] 2019-06-14 08:19
I've never seen extra files causing an issue, `__pycache__` perhaps might be an exception.
I've removed the files - still having the same issue.
```text
core-ssh:/config/custom_components/meross_cloud# ls -al
total 44
drwxr-xr-x    3 root     root          4096 Jun 14 18:15 .
drwxr-xr-x    8 root     root          4096 Jun 14 10:31 ..
-rw-r--r--    1 root     root          6448 Jun 14 10:31 __init__.py
-rw-r--r--    1 root     root          1203 Jun 14 10:31 common.py
-rw-r--r--    1 root     root          3185 Jun 14 10:31 cover.py
drwxr-xr-x    2 root     root          4096 Jun 14 10:31 extra
-rw-r--r--    1 root     root          3475 Jun 14 10:31 light.py
-rw-r--r--    1 root     root           239 Jun 14 10:31 manifest.json
-rw-r--r--    1 root     root          3073 Jun 14 10:31 sensor.py
-rw-r--r--    1 root     root          2548 Jun 14 10:31 switch.py
core-ssh:/config/custom_components/meross_cloud# hassio ha restart &
[1] 152
core-ssh:/config/custom_components/meross_cloud# tail -f /config/home-assistant.log | grep -i meross
2019-06-14 18:16:09 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-14 18:16:10 DEBUG (MainThread) [homeassistant.bootstrap] Setting up {'conversation', 'tuya', 'twilio', 'websocket_api', 'history', 'media_player', 'config', 'person', 'mqtt', 'sun', 'input_boolean', 'switch', 'hue', 'cloud', 'media_extractor', 'lifx', 'logbook', 'hassio', 'group', 'http', 'zeroconf', 'stream', 'sensor', 'googlehome', 'system_health', 'climate', 'device_tracker', 'zone', 'updater', 'openuv', 'input_number', 'esphome', 'panel_custom', 'google', 'automation', 'tts', 'shell_command', 'discovery', 'auth', 'scene', 'lovelace', 'frontend', 'google_assistant', 'binary_sensor', 'onboarding', 'influxdb', 'light', 'api', 'lametric', 'meross_cloud', 'weather', 'vera', 'unifi', 'notify', 'map', 'custom_updater', 'script', 'webhook', 'rest_command', 'cover', 'lock', 'input_select', 'cast'}
2019-06-14 18:16:12 ERROR (MainThread) [homeassistant.config] Unable to import meross_cloud: No module named 'common'
2019-06-14 18:16:12 ERROR (MainThread) [homeassistant.setup] Setup failed for meross_cloud: Invalid config.
```

**Comment by albertogeniola** [comment] 2019-06-14 10:55
Ok, I will look at it as soon as I get home. Keep in touch!

**Comment by albertogeniola** [comment] 2019-06-14 21:24
Alright, there were some bad imports to be refactored. Unfortunately on my debug environment they were working as expected (different paths). Could you please pull the latest version and try again?

**Comment by albertogeniola** [comment] 2019-06-16 14:01
Closing since the ticket opener confirmed it's now working as expected.

**Closed** 2019-06-16 14:02 UTC
Labels: bug
