### ISSUE TITLE
MSS420F not supported

### ISSUE THREAD

**Issue by dan1elhughes** [albertogeniola/meross-homeassistant#61] opened 2020-04-11 16:38 UTC
👋 Hiya, just installed this and all my other Meross devices are picked up just fine:

✅ `mss310 2.0.0 Firmware: 2.1.14`
✅ `mss425e 2.0.0 Firmware: 2.1.7`

However, the smart strip with the USBs onboard doesn't respond to any on/off toggles, and doesn't update in the UI when I turn it on or off from the app:

❌ `mss420f 3.0.0 Firmware: 3.1.1`

Happy to upload any other debugging info required. Thanks!

**Comment by albertogeniola** [comment] 2020-04-13 10:12
Hi @dan1elhughes ,

to help me add support for mss420f, you should run the [Meross Sniffer](https://github.com/albertogeniola/MerossIot#new-device-or-unsupported-features) utility. If you have python skills, that would be very easy: simply pull the master branch from this github repository and run the _meross_sniffer_ utility. If you have no experience with python, then you need to do the following:
- [Download and install python ](https://www.python.org/downloads/)
- Once installed, open a command prompt and type:
```bash
pip install meross_iot
```
- Then launch the sniffer utility from the command prompt:
```bash
meross_sniffer
```
- Follow the instructions to login. 

Once logged in, the prompt will tell you to play with the device using the Meross APP. At this point, you need to issue on/off commands using the APP (wait a bit after each command), then press ENTER to finish the capture session and eventually send the collected log to this thread. Such info would allow me to determine the reason why the device is not responding as expected.

**Comment by PabloTheNinja** [comment] 2020-04-14 08:44
I thought I would add my experience with the MSS420F strips. I have a RP4 running HA with HACS and the Meross component running. I have a Meross garage opener and 2 strips the component finds the strips and opener fine as does the Meross app. The issue is that the strips regularly go unavailable for periods of around an hour every 6 hours and without any restart or intervention return to the state before going unavailable - maybe a new case needs to be opened?

**Comment by PabloTheNinja** [comment] 2020-04-20 09:32
Update - since installation of MEross to HA MSS420F have experienced issues of unavailable, sice release 20200419.2 this is now fixed. Thanks!!

**Comment by albertogeniola** [comment] 2020-04-20 10:25
Glad to hear that. May I ask you which hardware and firmware version of the power strip you are using?

**Comment by albertogeniola** [comment] 2020-04-20 10:26
Glad to hear that

**Closed by albertogeniola** 2020-04-20 10:26 UTC
Labels: enhancement
