### ISSUE TITLE
Does it work with the Meross Smart Thermostat

### ISSUE THREAD

**Issue by ivanovd** [albertogeniola/meross-homeassistant#18] opened 2019-10-18 17:34 UTC
Apologies if that is not the right place to ask, but does this component support the Meross Smart Thermostat MTS100H?

![-203196686-196661871](https://user-images.githubusercontent.com/4889583/67115332-a1c00980-f1e6-11e9-886d-fb0cffd1f9e6.jpg)

**Comment by albertogeniola** [comment] 2019-11-18 07:43
Hi Ivanovd,
I am currently working in integrating the thermostat functionality on the low level library. As soon as that's ready, I can integrate it on HA. Keep in touch.

**Comment by ivanovd** [comment] 2019-12-02 09:25
@albertogeniola looking forward to testing it

**Comment by aferraz** [comment] 2019-12-02 09:30
@albertogeniola me too ;-)

**Comment by ivanovd** [comment] 2019-12-08 13:17
Hi Alberto. Any luck with that?

**Comment by albertogeniola** [comment] 2019-12-14 17:03
Hi guys, I'm currently developing the underlying MerossIot library that is needed by HomeAssistant custom component to enable smart valve integration. I'm almost 80% there, then I need to implement the integration with this library. Stay tuned, hopefully you'll get it from Santa by Christmas!

**Comment by ivanovd** [comment] 2019-12-23 23:26
I am waiting for Santa with a big bag of cookies :)

**Comment by albertogeniola** [comment] 2019-12-29 19:24
And Santa was here! 
I've just released a new version of the ha integration which adds support for Meross thermostats. Please give it a try and let me know if they work as expected. I must admit it required a lot of work to integrate such devices, but I guess it was worth it

**Comment by Mongomeri** [comment] 2019-12-30 13:45
Ciao Alberto, first of all congratulations for the work you did! I have gladly "contributed" to the cause.

I have configured since your release the 3 valves that I have at home and I must say that in reading the information Home Assistant (and HomeKit) they always give me precise values, unfortunately I cannot say the same when I try to change the configuration from HA: this results be almost impossible, I did numerous tests. If I set the valves to not active, it will be impossible for me to reactivate them (if not from the official Meross apps), if instead I set them to heating (which should be the manual mode, correct me if I'm wrong) the temperature setting is impossible (sometimes it produces changes, but in a way so random that it is impossible for me to understand the logic), but at least it allows me to return to automatic mode.
At the moment, finding myself outside the house where the valves are located, the raspberry (who is with me) on which the home assistant runs communicates completely remotely with the valves, I do not know if positioning it under the same network could work correctly.
I add that from Home Assistant I see that the commands given through it or HomeKit are correctly received.

Thanks and congratulations again!

**Comment by ivanovd** [comment] 2019-12-30 14:01
@Mongomeri I also have 3 thermostats and I have been playing with the HA integration since yesterday. Thanks to @albertogeniola for the timely release as he promised :)

I have noticed the same behavior as you - if you set the thermostat to inactive, you can only put it back in active mode through the Meross app. 

However, everything else works. Yes, it is not immediate, but that is due to the low power protocol that Meross uses to save the batteries of the thermostats. As per the official user manual the communication between the thermostat and the hub happens in up to 3 minute intervals, therefore the delay.

Today I have set up my first two automations and will see how that goes. For now they are time based - e.g. stop the heating when I am at work and start it one hour before I get home, but the next step is no change the trigger to GPS zone leave/enter.

When you have an automation you don't really care for the 3 minute delay since everything happens in the background, but I agree that if you are playing with the UI manually and you don't see the immediate change as you are used to then it is a bit annoying, but that is the Meross protocol, not Alberto to blame here.

**Comment by Mongomeri** [comment] 2019-12-30 14:33
@ivanovd Thanks for your feedback!

Yes, I am aware of the limits of the Meross implementation and protocol and of the actual sending of the commands to the valves every 3 minutes, but I can only switch from automatic to manual, without being able to change the set temperature: can you do it? Otherwise I can't understand which automations you may have set (in addition to those via the Meross app, of course). I could bypass the problem by constantly setting a high temperature for the automatic mode and a low one for the manual one (or vice versa), thus managing to switch from one to the other, but I wanted to understand if it was a limit of my configuration or given that my raspberry / HA is not currently under the same valve network.

One of my goals, given the low reliability of the thermometer implemented in the valves (especially in a valve placed behind a curtain, which tends to give very high values given the location on the valve itself) to associate an external thermometer placed in another place in the room and then, on the basis of the set time range, activate the valve on the basis of the real temperature detected. Unfortunately, apart from the work around I mentioned earlier, it does not seem directly feasible to me.

To conclude, is it a limitation of my implementation or system? :)

**Comment by ivanovd** [comment] 2019-12-30 14:45
I see your point now. My use case is like your workaround - I have set different temperatures for ECONOMY and HEAT and cycle between these two modes. I also have external thermometers and found out that the difference in the temperatures is about 1.5-2.0 degrees which for me is not a big deal.

I have tested to set the temperature manually via HA, but it doesn't change, so I can confirm your finding. I have no errors in the logs.

Maybe @albertogeniola can check this on his side and confirm. My thermostats, hub and HA are on the same network, so the limitation is not on your side.

**Comment by maltemosler** [comment] 2019-12-30 15:51
I have the same issue, I did some automations to turn the thermostat online/ offline when opening the window and its turning the thermostat off but when I try to activate it again it keeps beeing offline :( Only way to get it online is to use the meross app 😢 

- service: climate.turn_on
  data:
    entity_id: climate.badezimmer_heizung
- service: climate.set_preset_mode
    data:
      entity_id: climate.badezimmer_heizung
      preset_mode: 'HEAT'

**Comment by albertogeniola** [comment] 2019-12-30 22:00
OK guys, my bad. I would like to thank you all for the great and prompt feedback, that's what I needed. Unfortunately during my holidays I did not have my thermostat with me, so I had to "implement" it remotely, with no possibility to look at state propagation. Today I had the opportunity to have eyes on the thermostat and I was able to spot and fix the errors you mentioned. 

I've just released a new version of the library which fixes the following:
1. Ability to turn the thermostat ON once it's turned off (just press HEAT button or SCHEDULE BUTTON)
2. Setting target temperature for the thermostat

Please notice that the library won't behave exactly as the Meross App does. When you issue the command, the APP immediately assumes it has been received from the thermostat (event if it wasn't). With this component, HA the state only updates when the command is actually performed by the thermostat and not by the hub. This might not be user-friendly and probably will change in the future, but I'd like to keep it as it is right now as I like **state consistency**.

So, update the component and please let me know if everything works now.

**Comment by aferraz** [comment] 2019-12-30 23:20
@albertogeniola  this version work fine, you make a great job, thank you for your commitment

**Comment by albertogeniola** [comment] 2019-12-31 09:09
Awesome. Closing. Feel free to open new issues if something is not right.

**Closed by albertogeniola** 2019-12-31 09:09 UTC
Labels: Feature request

**Comment by carloslebreiro** [comment] 2021-01-16 18:28
Hi, every week or so I have problems with the thermostat as it does not fully closes the valve once the required temperature is reached. Eg. my top temperature is 22º, but sometimes it goes to 24º because it didn't fully closed the valve and the water continues to flow. So I take the batteries off, press the power button, then put the battery back on, press the up button and it will force it to calibrate. 
As you have built this based on a low level library it would be great if there was a command to force the valve to calibrate. 
Many thanks
